<!-- MHonArc v2.6.15 -->
<!--X-Subject: Re: Exception handlers -->
<!--X-From-R13: [nep Trryrl <srryrlNWDA.G[bagerny.QO> -->
<!--X-Date: Thu, 4 Jan 2001 21:48:50 &#45;0600 (CST) -->
<!--X-Message-Id: 200101050348.f053mme28560@trex.IRO.UMontreal.CA -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: Pine.OSF.4.21.0010231149290.18927&#45;100000@torni.hel.fi.ssh.com -->
<!--X-Head-End-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: Exception handlers</title>
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<hr>
[<a href="msg00004.html">Date Prev</a>][<a href="msg00006.html">Date Next</a>][<a href="msg00004.html">Thread Prev</a>][<a href="msg00006.html">Thread Next</a>][<a href="maillist.html#00005">Date Index</a>][<a href="threads.html#00005">Thread Index</a>]
<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h1>Re: Exception handlers</h1>
<hr>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul>
<li><em>To</em>: <a href="mailto:huima@DOMAIN.HIDDEN">huima@xxxxxxx</a></li>
<li><em>Subject</em>: Re: Exception handlers</li>
<li><em>From</em>: Marc Feeley &lt;<a href="mailto:feeley@DOMAIN.HIDDEN">feeley@xxxxxxxxxxxxxxxx</a>&gt;</li>
<li><em>Date</em>: Thu, 4 Jan 2001 22:48:48 -0500</li>
<li><em>Cc</em>: <a href="mailto:srfi-18@DOMAIN.HIDDEN">srfi-18@xxxxxxxxxxxxxxxxx</a>, <a href="mailto:srfi-21@DOMAIN.HIDDEN">srfi-21@xxxxxxxxxxxxxxxxx</a></li>
<li><em>In-reply-to</em>: &lt;<a href="mailto:Pine.OSF.4.21.0010231149290.18927-100000@DOMAIN.HIDDEN">Pine.OSF.4.21.0010231149290.18927-100000@xxxxxxxxxxxxxxxxxxxx</a>&gt;	(message from Antti Huima on Mon, 23 Oct 2000 12:14:02 +0300 (EET	DST))</li>
<li><em>References</em>: &lt;<a href="mailto:Pine.OSF.4.21.0010231149290.18927-100000@DOMAIN.HIDDEN">Pine.OSF.4.21.0010231149290.18927-100000@xxxxxxxxxxxxxxxxxxxx</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
<hr>
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre>&gt; Anyway, I think it is not beneficial that an exception handler can return
&gt; to the point of throwing the exception.
&gt; 
&gt; Assume that `open-input-file' raises an exception if a file is not found
&gt; and let:
&gt; 
&gt; (with-exception-handler
&gt;   (lambda (exception) (display &quot;Funny thing happened&quot;) (newline))
&gt;   (lambda ()
&gt;     (let ((port (open-input-file &quot;foo&quot;)))
&gt;       (read port))))
&gt; 
&gt; Executing this obviously causes `port' to be bound to an undefined value,
&gt; after which `read' will trigger an error that will typically be not an
&gt; exception but a full-blown crash (sort of).  I think that the common
&gt; intuition w/ exception handlers is that they do not return in the standard
&gt; way.  Now, as shown in the document, the exception handler can invoke an
&gt; explicitly captured escape continuation.  However, if
&gt; with-exception-handler would capture the continuation internally, its
&gt; implementation could be possibly optimized.  Moreover, this would inhibit
&gt; the problem above appearing.
&gt; 
&gt; Whatever exception systems will ever pop out, I would like to use such one
&gt; that would define with-exception-handler as:
&gt; 
&gt; (with-exception-handler handler thunk)                ;procedure
&gt; 
&gt;   Returns the result(s) of (thunk), unless an exception is (raise)d, in
&gt;   which case the continuation waiting for the value of (raise) is
&gt;   discarced, (handler exception) is called, and the value(s) of this call
&gt;   is (are) returned.  The number of values returned by (thunk) and 
&gt;   by (handler exception) for any exception must match the number of 
&gt;   values the continuation of the call to (with-exception-handler) expects
&gt;   to receive.

You have to know what you are doing when you use
&quot;with-exception-handler&quot;, so in a sense it is a low-level mechanism
for intercepting exceptions.  I agree that a more foolproof mechanism
would be useful for general use.  However, if there is only one
mechanism to intercept exceptions and it performs an implicit call/cc,
the mechanism will have a high cost on some systems, and it would be
unfortunate to force this high cost when a call/cc is not required.
There are also cases where you want the ability to restart the
computation that raised an exception.  For example, if the heap
overflows the exception handler may be able to free some useless
objects from a table and continue the allocation that caused a heap
overflow.  Similarly, you might want to write a debugger that will
suspend the computation when (load &quot;foo&quot;) does not find the file
&quot;foo&quot;, allowing the user to create that file and retry the &quot;load&quot;.
Check SRFI-21 for some more examples.

Marc

</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
<hr>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
<ul>
<li>Prev by Date:
<strong><a href="msg00004.html">New revisions</a></strong>
</li>
<li>Next by Date:
<strong><a href="msg00006.html">spurious wakeup from waiting on a condition variable</a></strong>
</li>
<li>Previous by thread:
<strong><a href="msg00004.html">New revisions</a></strong>
</li>
<li>Next by thread:
<strong><a href="msg00006.html">spurious wakeup from waiting on a condition variable</a></strong>
</li>
<li>Index(es):
<ul>
<li><a href="maillist.html#00005"><strong>Date</strong></a></li>
<li><a href="threads.html#00005"><strong>Thread</strong></a></li>
</ul>
</li>
</ul>

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
</body>
</html>
