<!-- MHonArc v2.6.15 -->
<!--X-Subject: Exception handlers -->
<!--X-From-R13: Oaggv Vhvzn <uhvznNffu.pbz> -->
<!--X-Date: Mon, 23 Oct 2000 04:14:05 &#45;0500 (CDT) -->
<!--X-Message-Id: Pine.OSF.4.21.0010231149290.18927&#45;100000@torni.hel.fi.ssh.com -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Exception handlers</title>
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<hr>
[<a href="msg00074.html">Date Prev</a>][<a href="msg00076.html">Date Next</a>][<a href="msg00069.html">Thread Prev</a>][<a href="msg00077.html">Thread Next</a>][<a href="maillist.html#00075">Date Index</a>][<a href="threads.html#00075">Thread Index</a>]
<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h1>Exception handlers</h1>
<p style="max-width: 30em;">This page is part of the web mail archives of <a href="http://srfi.schemers.org/srfi-18">SRFI 18</a> from before July 7th, 2015.  The new archives for SRFI 18 are <a href="http://srfi-email.schemers.org/srfi-18/">here</a>.  The new archives contain all messages, not just those from before July 7th, 2015.</p>
<hr>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul>
<li><em>To</em>: <a href="mailto:srfi-18@DOMAIN.HIDDEN">srfi-18@xxxxxxxxxxxxxxxxx</a></li>
<li><em>Subject</em>: Exception handlers</li>
<li><em>From</em>: Antti Huima &lt;<a href="mailto:huima@DOMAIN.HIDDEN">huima@xxxxxxx</a>&gt;</li>
<li><em>Date</em>: Mon, 23 Oct 2000 12:14:02 +0300 (EET DST)</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
<hr>
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre>It seems that this SRFI has overlived its draft period, so please throw
this to /dev/null if you wish.

Anyway, I think it is not beneficial that an exception handler can return
to the point of throwing the exception.

Assume that `open-input-file' raises an exception if a file is not found
and let:

(with-exception-handler
  (lambda (exception) (display &quot;Funny thing happened&quot;) (newline))
  (lambda ()
    (let ((port (open-input-file &quot;foo&quot;)))
      (read port))))

Executing this obviously causes `port' to be bound to an undefined value,
after which `read' will trigger an error that will typically be not an
exception but a full-blown crash (sort of).  I think that the common
intuition w/ exception handlers is that they do not return in the standard
way.  Now, as shown in the document, the exception handler can invoke an
explicitly captured escape continuation.  However, if
with-exception-handler would capture the continuation internally, its
implementation could be possibly optimized.  Moreover, this would inhibit
the problem above appearing.

Whatever exception systems will ever pop out, I would like to use such one
that would define with-exception-handler as:

(with-exception-handler handler thunk)                ;procedure

  Returns the result(s) of (thunk), unless an exception is (raise)d, in
  which case the continuation waiting for the value of (raise) is
  discarced, (handler exception) is called, and the value(s) of this call
  is (are) returned.  The number of values returned by (thunk) and 
  by (handler exception) for any exception must match the number of 
  values the continuation of the call to (with-exception-handler) expects
  to receive.

Because I like this :-] I thus propose the draft SRFI-18 to be changed
accordingly.

I think it should be also specified that the dynamic extent of `thunk' is
leaved when `handler' starts to execute.  The document was not clear on
this.  Otherwise e.g. (raise) inside `handler' will have undefined
behaviour.

Here an example implementation (assuming single return values), assuming
that the variable `handler' is bound to the current thread's exception
handler that (raise) will invoke.  `$$handler' is, in some magical way, a
thread-local global variable (to avoid assuming fluid-lets or whatever):

(define (with-exception-handler handler thunk)
  (let* ((unique (list #f))
	 (result
	  (call-with-current-continuation
	   (lambda (return)
	     (let ((internal-handler
		    (lambda (exc)
		      (return (cons unique exc))))
		   (old-handler $$handler))
	       (dynamic-wind
		   (lambda () (set! $$handler internal-handler))
		   thunk
		   (lambda () (set! $$handler old-handler))))))))
      (if (and (pair? result) (eq? (car result) unique))
	  (handler (cdr result))
	  result))))

This implementation restores the dynamic environment before handler starts
to execute in the way the Scheme implementatino would restore it
standardly after jumping to a captured continuation.
As opposed to this, the example from the draft:

              (define (g)
                (call-with-current-continuation
                  (lambda (return)
                    (with-exception-handler
                      (lambda (exc)
                        (return
                          (if (string? exc)
                              (string-append &quot;error: &quot; exc)
                              &quot;unknown error&quot;)))
                      (lambda ()
                        (write (f 4.))
                        (write (f -1.))
                        (write (f 9.)))))))

runs the handler in the dynamic environment of (thunk) which IMHO cannot
be correct in general.

-- 
Antti Huima

</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
<hr>
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00077" href="msg00077.html">Re: Exception handlers</a></strong>
<ul><li><em>From:</em> Marc Feeley</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
<ul>
<li>Prev by Date:
<strong><a href="msg00074.html">Re: threads &amp; dynamic environment &amp; continuations</a></strong>
</li>
<li>Next by Date:
<strong><a href="msg00076.html">New revisions</a></strong>
</li>
<li>Previous by thread:
<strong><a href="msg00069.html">real-time multithreading SRFI</a></strong>
</li>
<li>Next by thread:
<strong><a href="msg00077.html">Re: Exception handlers</a></strong>
</li>
<li>Index(es):
<ul>
<li><a href="maillist.html#00075"><strong>Date</strong></a></li>
<li><a href="threads.html#00075"><strong>Thread</strong></a></li>
</ul>
</li>
</ul>

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
</body>
</html>
